import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:just_audio/just_audio.dart';
import 'package:mp3_app/appTheme.dart';

import 'package:mp3_app/main.dart';
import 'package:mp3_app/presentation/Screens/Homepage/search.dart';
import 'package:mp3_app/presentation/widgets/playsound.dart';
import 'package:mp3_app/presentation/widgets/reciterProf.dart';

class Homepage extends StatelessWidget {
  static const String routeName = 'homepage';
  Homepage({super.key});
  final player = AudioPlayer();
  List<String> quranUrls = [
    "https://server10.mp3quran.net/minsh/001.mp3",
    "https://server10.mp3quran.net/minsh/002.mp3",
    "https://server10.mp3quran.net/minsh/003.mp3",
    "https://server10.mp3quran.net/minsh/004.mp3",
    "https://server10.mp3quran.net/minsh/005.mp3",
    "https://server10.mp3quran.net/minsh/006.mp3",
    "https://server10.mp3quran.net/minsh/007.mp3",
    "https://server10.mp3quran.net/minsh/008.mp3",
    "https://server10.mp3quran.net/minsh/009.mp3",
    "https://server10.mp3quran.net/minsh/010.mp3",
    "https://server10.mp3quran.net/minsh/011.mp3",
    "https://server10.mp3quran.net/minsh/012.mp3",
    "https://server10.mp3quran.net/minsh/013.mp3",
    "https://server10.mp3quran.net/minsh/014.mp3",
    "https://server10.mp3quran.net/minsh/015.mp3",
    "https://server10.mp3quran.net/minsh/016.mp3",
    "https://server10.mp3quran.net/minsh/017.mp3",
    "https://server10.mp3quran.net/minsh/018.mp3",
    "https://server10.mp3quran.net/minsh/019.mp3",
    "https://server10.mp3quran.net/minsh/020.mp3",
    "https://server10.mp3quran.net/minsh/021.mp3",
    "https://server10.mp3quran.net/minsh/022.mp3",
    "https://server10.mp3quran.net/minsh/023.mp3",
    "https://server10.mp3quran.net/minsh/024.mp3",
    "https://server10.mp3quran.net/minsh/025.mp3",
    "https://server10.mp3quran.net/minsh/026.mp3",
    "https://server10.mp3quran.net/minsh/027.mp3",
    "https://server10.mp3quran.net/minsh/028.mp3",
    "https://server10.mp3quran.net/minsh/029.mp3",
    "https://server10.mp3quran.net/minsh/030.mp3",
    "https://server10.mp3quran.net/minsh/031.mp3",
    "https://server10.mp3quran.net/minsh/032.mp3",
    "https://server10.mp3quran.net/minsh/033.mp3",
    "https://server10.mp3quran.net/minsh/034.mp3",
    "https://server10.mp3quran.net/minsh/035.mp3",
    "https://server10.mp3quran.net/minsh/036.mp3",
    "https://server10.mp3quran.net/minsh/037.mp3",
    "https://server10.mp3quran.net/minsh/038.mp3",
    "https://server10.mp3quran.net/minsh/039.mp3",
    "https://server10.mp3quran.net/minsh/040.mp3",
    "https://server10.mp3quran.net/minsh/041.mp3",
    "https://server10.mp3quran.net/minsh/042.mp3",
    "https://server10.mp3quran.net/minsh/043.mp3",
    "https://server10.mp3quran.net/minsh/044.mp3",
    "https://server10.mp3quran.net/minsh/045.mp3",
    "https://server10.mp3quran.net/minsh/046.mp3",
    "https://server10.mp3quran.net/minsh/047.mp3",
    "https://server10.mp3quran.net/minsh/048.mp3",
    "https://server10.mp3quran.net/minsh/049.mp3",
    "https://server10.mp3quran.net/minsh/050.mp3",
    "https://server10.mp3quran.net/minsh/051.mp3",
    "https://server10.mp3quran.net/minsh/052.mp3",
    "https://server10.mp3quran.net/minsh/053.mp3",
    "https://server10.mp3quran.net/minsh/054.mp3",
    "https://server10.mp3quran.net/minsh/055.mp3",
    "https://server10.mp3quran.net/minsh/056.mp3",
    "https://server10.mp3quran.net/minsh/057.mp3",
    "https://server10.mp3quran.net/minsh/058.mp3",
    "https://server10.mp3quran.net/minsh/059.mp3",
    "https://server10.mp3quran.net/minsh/060.mp3",
    "https://server10.mp3quran.net/minsh/061.mp3",
    "https://server10.mp3quran.net/minsh/062.mp3",
    "https://server10.mp3quran.net/minsh/063.mp3",
    "https://server10.mp3quran.net/minsh/064.mp3",
    "https://server10.mp3quran.net/minsh/065.mp3",
    "https://server10.mp3quran.net/minsh/066.mp3",
    "https://server10.mp3quran.net/minsh/067.mp3",
    "https://server10.mp3quran.net/minsh/068.mp3",
    "https://server10.mp3quran.net/minsh/069.mp3",
    "https://server10.mp3quran.net/minsh/070.mp3",
    "https://server10.mp3quran.net/minsh/071.mp3",
    "https://server10.mp3quran.net/minsh/072.mp3",
    "https://server10.mp3quran.net/minsh/073.mp3",
    "https://server10.mp3quran.net/minsh/074.mp3",
    "https://server10.mp3quran.net/minsh/075.mp3",
    "https://server10.mp3quran.net/minsh/076.mp3",
    "https://server10.mp3quran.net/minsh/077.mp3",
    "https://server10.mp3quran.net/minsh/078.mp3",
    "https://server10.mp3quran.net/minsh/079.mp3",
    "https://server10.mp3quran.net/minsh/080.mp3",
    "https://server10.mp3quran.net/minsh/081.mp3",
    "https://server10.mp3quran.net/minsh/082.mp3",
    "https://server10.mp3quran.net/minsh/083.mp3",
    "https://server10.mp3quran.net/minsh/084.mp3",
    "https://server10.mp3quran.net/minsh/085.mp3",
    "https://server10.mp3quran.net/minsh/086.mp3",
    "https://server10.mp3quran.net/minsh/087.mp3",
    "https://server10.mp3quran.net/minsh/088.mp3",
    "https://server10.mp3quran.net/minsh/089.mp3",
    "https://server10.mp3quran.net/minsh/090.mp3",
    "https://server10.mp3quran.net/minsh/091.mp3",
    "https://server10.mp3quran.net/minsh/092.mp3",
    "https://server10.mp3quran.net/minsh/093.mp3",
    "https://server10.mp3quran.net/minsh/094.mp3",
    "https://server10.mp3quran.net/minsh/095.mp3",
    "https://server10.mp3quran.net/minsh/096.mp3",
    "https://server10.mp3quran.net/minsh/097.mp3",
    "https://server10.mp3quran.net/minsh/098.mp3",
    "https://server10.mp3quran.net/minsh/099.mp3",
    "https://server10.mp3quran.net/minsh/100.mp3",
    "https://server10.mp3quran.net/minsh/101.mp3",
    "https://server10.mp3quran.net/minsh/102.mp3",
    "https://server10.mp3quran.net/minsh/103.mp3",
    "https://server10.mp3quran.net/minsh/104.mp3",
    "https://server10.mp3quran.net/minsh/105.mp3",
    "https://server10.mp3quran.net/minsh/106.mp3",
    "https://server10.mp3quran.net/minsh/107.mp3",
    "https://server10.mp3quran.net/minsh/108.mp3",
    "https://server10.mp3quran.net/minsh/109.mp3",
    "https://server10.mp3quran.net/minsh/110.mp3",
    "https://server10.mp3quran.net/minsh/111.mp3",
    "https://server10.mp3quran.net/minsh/112.mp3",
    "https://server10.mp3quran.net/minsh/113.mp3",
    "https://server10.mp3quran.net/minsh/114.mp3",
  ];
  List<String> quranSurahs = [
    "الفاتحة",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النور",
    "الفرقان",
    "الشعراء",
    "النمل",
    "القصص",
    "العنكبوت",
    "الروم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصلت",
    "الشورى",
    "الزخرف",
    "الدخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    " الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "طلاق",
    "التحريم",
    "الملك",
    "القلم",
    "المعارج",
    "نوح",
    " الجن",
    "المزمل",
    "مدثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "نبأ",
    "نازعات",
    "عبس",
    " التكوير",
    " الإنفطار",
    "المطففين",
    " الإنشقاق",
    "البروج",
    " الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العصر",
    "همزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xff1C1B1B),
      body: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              height: 60.h,
            ),
            Row(
              // mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                    onPressed: () {
                      Navigator.pushNamed(context, Search.routeName);
                    },
                    icon: Icon(
                      Icons.search_outlined,
                      size: 30.sp,
                      color: Appcolors.whiteColor,
                    )),
              ],
            ),
            SizedBox(
              height: 30.h,
            ),
            Center(
                child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Reciterprof(
                audio: 'https://server10.mp3quran.net/minsh/001.mp3',
                imageUrl: 'assets/mohamed-seddik-el-menchaoui-154.jpg',
              ),
            )),
            SizedBox(
              height: 20.h,
            ),
            Text(
              'PlayList',
              style: TextStyle(
                  color: Colors.white,
                  fontFamily: Fontstyle.fontname,
                  fontSize: 20),
            ),
            SizedBox(
              height: 10.h,
            ),
            Container(
                height: 400.h,
                width: double.infinity,
                child: ListView.builder(
                  itemCount: quranUrls.length,
                  itemBuilder: (context, index) {
                    return Column(
                      children: [
                        CustomPlaysound(
                          surah: quranSurahs[index],
                          reciter: 'محمد صديق المنشاوي',
                          audio: quranUrls[index],
                        ),
                      ],
                    );
                  },
                ))
          ],
        ),
      ),
    );
  }
}
