// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOOzq5gRrer4qgyN2R75alEQ5oFFrdqK0',
    appId: '1:550585436528:web:3bfae65e25406a452d67b5',
    messagingSenderId: '550585436528',
    projectId: 'noonapp-90ada',
    authDomain: 'noonapp-90ada.firebaseapp.com',
    storageBucket: 'noonapp-90ada.appspot.com',
    measurementId: 'G-Z36ECRD8E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2NYT2aMNM8j4HOOfuQrWwqgg0MXM0A0',
    appId: '1:550585436528:android:db68468d3c41ca7d2d67b5',
    messagingSenderId: '550585436528',
    projectId: 'noonapp-90ada',
    storageBucket: 'noonapp-90ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6RqLMBi0TCI4hAP7_o6q2UyhCcmO8vbA',
    appId: '1:550585436528:ios:33807a99ee58b5052d67b5',
    messagingSenderId: '550585436528',
    projectId: 'noonapp-90ada',
    storageBucket: 'noonapp-90ada.appspot.com',
    iosBundleId: 'com.example.mp3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6RqLMBi0TCI4hAP7_o6q2UyhCcmO8vbA',
    appId: '1:550585436528:ios:33807a99ee58b5052d67b5',
    messagingSenderId: '550585436528',
    projectId: 'noonapp-90ada',
    storageBucket: 'noonapp-90ada.appspot.com',
    iosBundleId: 'com.example.mp3App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOOzq5gRrer4qgyN2R75alEQ5oFFrdqK0',
    appId: '1:550585436528:web:ecff937ffdbc029b2d67b5',
    messagingSenderId: '550585436528',
    projectId: 'noonapp-90ada',
    authDomain: 'noonapp-90ada.firebaseapp.com',
    storageBucket: 'noonapp-90ada.appspot.com',
    measurementId: 'G-CHWLJMMBG3',
  );

}